/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as DocumentationRouteRouteImport } from './routes/_documentation/route'
import { Route as ChatbotRouteRouteImport } from './routes/_chatbot/route'
import { Route as AuthenticationRouteRouteImport } from './routes/_authentication/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiTrpcRouteImport } from './routes/api/trpc'
import { Route as ApiRevalidateRouteImport } from './routes/api/revalidate'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ProtectedScreeningsRouteImport } from './routes/_protected/screenings'
import { Route as ProtectedNewRouteImport } from './routes/_protected/new'
import { Route as ProtectedJobsRouteImport } from './routes/_protected/jobs'
import { Route as ProtectedInvestorsRouteImport } from './routes/_protected/investors'
import { Route as ProtectedHealthRouteImport } from './routes/_protected/health'
import { Route as ProtectedDocumentsRouteImport } from './routes/_protected/documents'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAnalyticsRouteImport } from './routes/_protected/analytics'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as DocumentationDocsRouteImport } from './routes/_documentation/docs'
import { Route as ChatbotChatRouteImport } from './routes/_chatbot/chat'
import { Route as ProtectedScreenersIndexRouteImport } from './routes/_protected/screeners/index'
import { Route as ProtectedLeadsIndexRouteImport } from './routes/_protected/leads/index'
import { Route as ProtectedInvestorLeadsIndexRouteImport } from './routes/_protected/investor-leads/index'
import { Route as ProtectedInvestmentThemesIndexRouteImport } from './routes/_protected/investment-themes/index'
import { Route as ProtectedDealOpportunitiesIndexRouteImport } from './routes/_protected/deal-opportunities/index'
import { Route as ProtectedCompaniesIndexRouteImport } from './routes/_protected/companies/index'
import { Route as ProtectedCimScreeningIndexRouteImport } from './routes/_protected/cim-screening/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiLeadsIngestRouteImport } from './routes/api/leads/ingest'
import { Route as ApiInvestorLeadsIngestRouteImport } from './routes/api/investor-leads/ingest'
import { Route as ApiHealthRedisRouteImport } from './routes/api/health/redis'
import { Route as ApiDealOpportunitiesQuickAddRouteImport } from './routes/api/deal-opportunities/quick-add'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedScreenersUidRouteImport } from './routes/_protected/screeners/$uid'
import { Route as ProtectedProfileUidRouteImport } from './routes/_protected/profile/$uid'
import { Route as ProtectedNewDocumentRouteImport } from './routes/_protected/new/document'
import { Route as ProtectedLeadsNewRouteImport } from './routes/_protected/leads/new'
import { Route as ProtectedInvestorsNewRouteImport } from './routes/_protected/investors/new'
import { Route as ProtectedInvestorLeadsNewRouteImport } from './routes/_protected/investor-leads/new'
import { Route as ProtectedInvestmentThemesNewRouteImport } from './routes/_protected/investment-themes/new'
import { Route as ProtectedDealOpportunitiesQuickAddRouteImport } from './routes/_protected/deal-opportunities/quick-add'
import { Route as ProtectedDealOpportunitiesNewRouteImport } from './routes/_protected/deal-opportunities/new'
import { Route as ProtectedCompaniesNewRouteImport } from './routes/_protected/companies/new'
import { Route as ProtectedCompaniesUidRouteImport } from './routes/_protected/companies/$uid'
import { Route as ProtectedCimScreeningSessionIdRouteImport } from './routes/_protected/cim-screening/$sessionId'
import { Route as DocumentationDocsThemesRouteImport } from './routes/_documentation/docs/themes'
import { Route as DocumentationDocsScreeningsRouteImport } from './routes/_documentation/docs/screenings'
import { Route as DocumentationDocsLeadsRouteImport } from './routes/_documentation/docs/leads'
import { Route as DocumentationDocsJobsRouteImport } from './routes/_documentation/docs/jobs'
import { Route as DocumentationDocsInvestorsRouteImport } from './routes/_documentation/docs/investors'
import { Route as DocumentationDocsGettingStartedRouteImport } from './routes/_documentation/docs/getting-started'
import { Route as DocumentationDocsFaqRouteImport } from './routes/_documentation/docs/faq'
import { Route as DocumentationDocsDocumentsRouteImport } from './routes/_documentation/docs/documents'
import { Route as DocumentationDocsDealsRouteImport } from './routes/_documentation/docs/deals'
import { Route as DocumentationDocsCompaniesRouteImport } from './routes/_documentation/docs/companies'
import { Route as DocumentationDocsChatRouteImport } from './routes/_documentation/docs/chat'
import { Route as DocumentationDocsAnalyticsRouteImport } from './routes/_documentation/docs/analytics'
import { Route as DocumentationDocsAdminRouteImport } from './routes/_documentation/docs/admin'
import { Route as ChatbotChatIdRouteImport } from './routes/_chatbot/chat/$id'
import { Route as AuthenticationAuthVerifyEmailRouteImport } from './routes/_authentication/auth/verify-email'
import { Route as AuthenticationAuthSignupRouteImport } from './routes/_authentication/auth/signup'
import { Route as AuthenticationAuthResetPasswordRouteImport } from './routes/_authentication/auth/reset-password'
import { Route as AuthenticationAuthLoginRouteImport } from './routes/_authentication/auth/login'
import { Route as AuthenticationAuthForgotPasswordRouteImport } from './routes/_authentication/auth/forgot-password'
import { Route as AuthenticationAuthErrorRouteImport } from './routes/_authentication/auth/error'
import { Route as ProtectedLeadsUidIndexRouteImport } from './routes/_protected/leads/$uid/index'
import { Route as ProtectedInvestorsUidIndexRouteImport } from './routes/_protected/investors/$uid/index'
import { Route as ProtectedInvestorLeadsUidIndexRouteImport } from './routes/_protected/investor-leads/$uid/index'
import { Route as ProtectedInvestmentThemesUidIndexRouteImport } from './routes/_protected/investment-themes/$uid/index'
import { Route as ProtectedDealOpportunitiesUidIndexRouteImport } from './routes/_protected/deal-opportunities/$uid/index'
import { Route as ProtectedLeadsUidEditRouteImport } from './routes/_protected/leads/$uid/edit'
import { Route as ProtectedLeadsUidConvertRouteImport } from './routes/_protected/leads/$uid/convert'
import { Route as ProtectedInvestorsUidEditRouteImport } from './routes/_protected/investors/$uid/edit'
import { Route as ProtectedInvestorLeadsUidEditRouteImport } from './routes/_protected/investor-leads/$uid/edit'
import { Route as ProtectedInvestorLeadsUidConvertRouteImport } from './routes/_protected/investor-leads/$uid/convert'
import { Route as ProtectedInvestmentThemesUidEditRouteImport } from './routes/_protected/investment-themes/$uid/edit'
import { Route as ProtectedDealOpportunitiesUidEditRouteImport } from './routes/_protected/deal-opportunities/$uid/edit'
import { Route as ProtectedCompaniesUidEditRouteImport } from './routes/_protected/companies/$uid/edit'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationRouteRoute = DocumentationRouteRouteImport.update({
  id: '/_documentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRouteRoute = ChatbotRouteRouteImport.update({
  id: '/_chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRouteRoute = AuthenticationRouteRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiTrpcRoute = ApiTrpcRouteImport.update({
  id: '/api/trpc',
  path: '/api/trpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedScreeningsRoute = ProtectedScreeningsRouteImport.update({
  id: '/screenings',
  path: '/screenings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedNewRoute = ProtectedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedJobsRoute = ProtectedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInvestorsRoute = ProtectedInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHealthRoute = ProtectedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDocumentsRoute = ProtectedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAnalyticsRoute = ProtectedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const DocumentationDocsRoute = DocumentationDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DocumentationRouteRoute,
} as any)
const ChatbotChatRoute = ChatbotChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ChatbotRouteRoute,
} as any)
const ProtectedScreenersIndexRoute = ProtectedScreenersIndexRouteImport.update({
  id: '/screeners/',
  path: '/screeners/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLeadsIndexRoute = ProtectedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInvestorLeadsIndexRoute =
  ProtectedInvestorLeadsIndexRouteImport.update({
    id: '/investor-leads/',
    path: '/investor-leads/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInvestmentThemesIndexRoute =
  ProtectedInvestmentThemesIndexRouteImport.update({
    id: '/investment-themes/',
    path: '/investment-themes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDealOpportunitiesIndexRoute =
  ProtectedDealOpportunitiesIndexRouteImport.update({
    id: '/deal-opportunities/',
    path: '/deal-opportunities/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCompaniesIndexRoute = ProtectedCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCimScreeningIndexRoute =
  ProtectedCimScreeningIndexRouteImport.update({
    id: '/cim-screening/',
    path: '/cim-screening/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiTrpcRoute,
} as any)
const ApiLeadsIngestRoute = ApiLeadsIngestRouteImport.update({
  id: '/api/leads/ingest',
  path: '/api/leads/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvestorLeadsIngestRoute = ApiInvestorLeadsIngestRouteImport.update({
  id: '/api/investor-leads/ingest',
  path: '/api/investor-leads/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRedisRoute = ApiHealthRedisRouteImport.update({
  id: '/api/health/redis',
  path: '/api/health/redis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDealOpportunitiesQuickAddRoute =
  ApiDealOpportunitiesQuickAddRouteImport.update({
    id: '/api/deal-opportunities/quick-add',
    path: '/api/deal-opportunities/quick-add',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedScreenersUidRoute = ProtectedScreenersUidRouteImport.update({
  id: '/screeners/$uid',
  path: '/screeners/$uid',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileUidRoute = ProtectedProfileUidRouteImport.update({
  id: '/profile/$uid',
  path: '/profile/$uid',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedNewDocumentRoute = ProtectedNewDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => ProtectedNewRoute,
} as any)
const ProtectedLeadsNewRoute = ProtectedLeadsNewRouteImport.update({
  id: '/leads/new',
  path: '/leads/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInvestorsNewRoute = ProtectedInvestorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedInvestorsRoute,
} as any)
const ProtectedInvestorLeadsNewRoute =
  ProtectedInvestorLeadsNewRouteImport.update({
    id: '/investor-leads/new',
    path: '/investor-leads/new',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInvestmentThemesNewRoute =
  ProtectedInvestmentThemesNewRouteImport.update({
    id: '/investment-themes/new',
    path: '/investment-themes/new',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDealOpportunitiesQuickAddRoute =
  ProtectedDealOpportunitiesQuickAddRouteImport.update({
    id: '/deal-opportunities/quick-add',
    path: '/deal-opportunities/quick-add',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDealOpportunitiesNewRoute =
  ProtectedDealOpportunitiesNewRouteImport.update({
    id: '/deal-opportunities/new',
    path: '/deal-opportunities/new',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCompaniesNewRoute = ProtectedCompaniesNewRouteImport.update({
  id: '/companies/new',
  path: '/companies/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCompaniesUidRoute = ProtectedCompaniesUidRouteImport.update({
  id: '/companies/$uid',
  path: '/companies/$uid',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCimScreeningSessionIdRoute =
  ProtectedCimScreeningSessionIdRouteImport.update({
    id: '/cim-screening/$sessionId',
    path: '/cim-screening/$sessionId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const DocumentationDocsThemesRoute = DocumentationDocsThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => DocumentationDocsRoute,
} as any)
const DocumentationDocsScreeningsRoute =
  DocumentationDocsScreeningsRouteImport.update({
    id: '/screenings',
    path: '/screenings',
    getParentRoute: () => DocumentationDocsRoute,
  } as any)
const DocumentationDocsLeadsRoute = DocumentationDocsLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DocumentationDocsRoute,
} as any)
const DocumentationDocsJobsRoute = DocumentationDocsJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DocumentationDocsRoute,
} as any)
const DocumentationDocsInvestorsRoute =
  DocumentationDocsInvestorsRouteImport.update({
    id: '/investors',
    path: '/investors',
    getParentRoute: () => DocumentationDocsRoute,
  } as any)
const DocumentationDocsGettingStartedRoute =
  DocumentationDocsGettingStartedRouteImport.update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => DocumentationDocsRoute,
  } as any)
const DocumentationDocsFaqRoute = DocumentationDocsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => DocumentationDocsRoute,
} as any)
const DocumentationDocsDocumentsRoute =
  DocumentationDocsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => DocumentationDocsRoute,
  } as any)
const DocumentationDocsDealsRoute = DocumentationDocsDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => DocumentationDocsRoute,
} as any)
const DocumentationDocsCompaniesRoute =
  DocumentationDocsCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => DocumentationDocsRoute,
  } as any)
const DocumentationDocsChatRoute = DocumentationDocsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DocumentationDocsRoute,
} as any)
const DocumentationDocsAnalyticsRoute =
  DocumentationDocsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DocumentationDocsRoute,
  } as any)
const DocumentationDocsAdminRoute = DocumentationDocsAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DocumentationDocsRoute,
} as any)
const ChatbotChatIdRoute = ChatbotChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatbotChatRoute,
} as any)
const AuthenticationAuthVerifyEmailRoute =
  AuthenticationAuthVerifyEmailRouteImport.update({
    id: '/auth/verify-email',
    path: '/auth/verify-email',
    getParentRoute: () => AuthenticationRouteRoute,
  } as any)
const AuthenticationAuthSignupRoute =
  AuthenticationAuthSignupRouteImport.update({
    id: '/auth/signup',
    path: '/auth/signup',
    getParentRoute: () => AuthenticationRouteRoute,
  } as any)
const AuthenticationAuthResetPasswordRoute =
  AuthenticationAuthResetPasswordRouteImport.update({
    id: '/auth/reset-password',
    path: '/auth/reset-password',
    getParentRoute: () => AuthenticationRouteRoute,
  } as any)
const AuthenticationAuthLoginRoute = AuthenticationAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthenticationRouteRoute,
} as any)
const AuthenticationAuthForgotPasswordRoute =
  AuthenticationAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => AuthenticationRouteRoute,
  } as any)
const AuthenticationAuthErrorRoute = AuthenticationAuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => AuthenticationRouteRoute,
} as any)
const ProtectedLeadsUidIndexRoute = ProtectedLeadsUidIndexRouteImport.update({
  id: '/leads/$uid/',
  path: '/leads/$uid/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInvestorsUidIndexRoute =
  ProtectedInvestorsUidIndexRouteImport.update({
    id: '/$uid/',
    path: '/$uid/',
    getParentRoute: () => ProtectedInvestorsRoute,
  } as any)
const ProtectedInvestorLeadsUidIndexRoute =
  ProtectedInvestorLeadsUidIndexRouteImport.update({
    id: '/investor-leads/$uid/',
    path: '/investor-leads/$uid/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInvestmentThemesUidIndexRoute =
  ProtectedInvestmentThemesUidIndexRouteImport.update({
    id: '/investment-themes/$uid/',
    path: '/investment-themes/$uid/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDealOpportunitiesUidIndexRoute =
  ProtectedDealOpportunitiesUidIndexRouteImport.update({
    id: '/deal-opportunities/$uid/',
    path: '/deal-opportunities/$uid/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedLeadsUidEditRoute = ProtectedLeadsUidEditRouteImport.update({
  id: '/leads/$uid/edit',
  path: '/leads/$uid/edit',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLeadsUidConvertRoute =
  ProtectedLeadsUidConvertRouteImport.update({
    id: '/leads/$uid/convert',
    path: '/leads/$uid/convert',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInvestorsUidEditRoute =
  ProtectedInvestorsUidEditRouteImport.update({
    id: '/$uid/edit',
    path: '/$uid/edit',
    getParentRoute: () => ProtectedInvestorsRoute,
  } as any)
const ProtectedInvestorLeadsUidEditRoute =
  ProtectedInvestorLeadsUidEditRouteImport.update({
    id: '/investor-leads/$uid/edit',
    path: '/investor-leads/$uid/edit',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInvestorLeadsUidConvertRoute =
  ProtectedInvestorLeadsUidConvertRouteImport.update({
    id: '/investor-leads/$uid/convert',
    path: '/investor-leads/$uid/convert',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInvestmentThemesUidEditRoute =
  ProtectedInvestmentThemesUidEditRouteImport.update({
    id: '/investment-themes/$uid/edit',
    path: '/investment-themes/$uid/edit',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDealOpportunitiesUidEditRoute =
  ProtectedDealOpportunitiesUidEditRouteImport.update({
    id: '/deal-opportunities/$uid/edit',
    path: '/deal-opportunities/$uid/edit',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedCompaniesUidEditRoute =
  ProtectedCompaniesUidEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedCompaniesUidRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/chat': typeof ChatbotChatRouteWithChildren
  '/docs': typeof DocumentationDocsRouteWithChildren
  '/admin': typeof ProtectedAdminRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/documents': typeof ProtectedDocumentsRoute
  '/health': typeof ProtectedHealthRoute
  '/investors': typeof ProtectedInvestorsRouteWithChildren
  '/jobs': typeof ProtectedJobsRoute
  '/new': typeof ProtectedNewRouteWithChildren
  '/screenings': typeof ProtectedScreeningsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/trpc': typeof ApiTrpcRouteWithChildren
  '/auth/error': typeof AuthenticationAuthErrorRoute
  '/auth/forgot-password': typeof AuthenticationAuthForgotPasswordRoute
  '/auth/login': typeof AuthenticationAuthLoginRoute
  '/auth/reset-password': typeof AuthenticationAuthResetPasswordRoute
  '/auth/signup': typeof AuthenticationAuthSignupRoute
  '/auth/verify-email': typeof AuthenticationAuthVerifyEmailRoute
  '/chat/$id': typeof ChatbotChatIdRoute
  '/docs/admin': typeof DocumentationDocsAdminRoute
  '/docs/analytics': typeof DocumentationDocsAnalyticsRoute
  '/docs/chat': typeof DocumentationDocsChatRoute
  '/docs/companies': typeof DocumentationDocsCompaniesRoute
  '/docs/deals': typeof DocumentationDocsDealsRoute
  '/docs/documents': typeof DocumentationDocsDocumentsRoute
  '/docs/faq': typeof DocumentationDocsFaqRoute
  '/docs/getting-started': typeof DocumentationDocsGettingStartedRoute
  '/docs/investors': typeof DocumentationDocsInvestorsRoute
  '/docs/jobs': typeof DocumentationDocsJobsRoute
  '/docs/leads': typeof DocumentationDocsLeadsRoute
  '/docs/screenings': typeof DocumentationDocsScreeningsRoute
  '/docs/themes': typeof DocumentationDocsThemesRoute
  '/cim-screening/$sessionId': typeof ProtectedCimScreeningSessionIdRoute
  '/companies/$uid': typeof ProtectedCompaniesUidRouteWithChildren
  '/companies/new': typeof ProtectedCompaniesNewRoute
  '/deal-opportunities/new': typeof ProtectedDealOpportunitiesNewRoute
  '/deal-opportunities/quick-add': typeof ProtectedDealOpportunitiesQuickAddRoute
  '/investment-themes/new': typeof ProtectedInvestmentThemesNewRoute
  '/investor-leads/new': typeof ProtectedInvestorLeadsNewRoute
  '/investors/new': typeof ProtectedInvestorsNewRoute
  '/leads/new': typeof ProtectedLeadsNewRoute
  '/new/document': typeof ProtectedNewDocumentRoute
  '/profile/$uid': typeof ProtectedProfileUidRoute
  '/screeners/$uid': typeof ProtectedScreenersUidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/deal-opportunities/quick-add': typeof ApiDealOpportunitiesQuickAddRoute
  '/api/health/redis': typeof ApiHealthRedisRoute
  '/api/investor-leads/ingest': typeof ApiInvestorLeadsIngestRoute
  '/api/leads/ingest': typeof ApiLeadsIngestRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/cim-screening/': typeof ProtectedCimScreeningIndexRoute
  '/companies/': typeof ProtectedCompaniesIndexRoute
  '/deal-opportunities/': typeof ProtectedDealOpportunitiesIndexRoute
  '/investment-themes/': typeof ProtectedInvestmentThemesIndexRoute
  '/investor-leads/': typeof ProtectedInvestorLeadsIndexRoute
  '/leads/': typeof ProtectedLeadsIndexRoute
  '/screeners/': typeof ProtectedScreenersIndexRoute
  '/companies/$uid/edit': typeof ProtectedCompaniesUidEditRoute
  '/deal-opportunities/$uid/edit': typeof ProtectedDealOpportunitiesUidEditRoute
  '/investment-themes/$uid/edit': typeof ProtectedInvestmentThemesUidEditRoute
  '/investor-leads/$uid/convert': typeof ProtectedInvestorLeadsUidConvertRoute
  '/investor-leads/$uid/edit': typeof ProtectedInvestorLeadsUidEditRoute
  '/investors/$uid/edit': typeof ProtectedInvestorsUidEditRoute
  '/leads/$uid/convert': typeof ProtectedLeadsUidConvertRoute
  '/leads/$uid/edit': typeof ProtectedLeadsUidEditRoute
  '/deal-opportunities/$uid/': typeof ProtectedDealOpportunitiesUidIndexRoute
  '/investment-themes/$uid/': typeof ProtectedInvestmentThemesUidIndexRoute
  '/investor-leads/$uid/': typeof ProtectedInvestorLeadsUidIndexRoute
  '/investors/$uid/': typeof ProtectedInvestorsUidIndexRoute
  '/leads/$uid/': typeof ProtectedLeadsUidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/chat': typeof ChatbotChatRouteWithChildren
  '/docs': typeof DocumentationDocsRouteWithChildren
  '/admin': typeof ProtectedAdminRoute
  '/analytics': typeof ProtectedAnalyticsRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/documents': typeof ProtectedDocumentsRoute
  '/health': typeof ProtectedHealthRoute
  '/investors': typeof ProtectedInvestorsRouteWithChildren
  '/jobs': typeof ProtectedJobsRoute
  '/new': typeof ProtectedNewRouteWithChildren
  '/screenings': typeof ProtectedScreeningsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/trpc': typeof ApiTrpcRouteWithChildren
  '/auth/error': typeof AuthenticationAuthErrorRoute
  '/auth/forgot-password': typeof AuthenticationAuthForgotPasswordRoute
  '/auth/login': typeof AuthenticationAuthLoginRoute
  '/auth/reset-password': typeof AuthenticationAuthResetPasswordRoute
  '/auth/signup': typeof AuthenticationAuthSignupRoute
  '/auth/verify-email': typeof AuthenticationAuthVerifyEmailRoute
  '/chat/$id': typeof ChatbotChatIdRoute
  '/docs/admin': typeof DocumentationDocsAdminRoute
  '/docs/analytics': typeof DocumentationDocsAnalyticsRoute
  '/docs/chat': typeof DocumentationDocsChatRoute
  '/docs/companies': typeof DocumentationDocsCompaniesRoute
  '/docs/deals': typeof DocumentationDocsDealsRoute
  '/docs/documents': typeof DocumentationDocsDocumentsRoute
  '/docs/faq': typeof DocumentationDocsFaqRoute
  '/docs/getting-started': typeof DocumentationDocsGettingStartedRoute
  '/docs/investors': typeof DocumentationDocsInvestorsRoute
  '/docs/jobs': typeof DocumentationDocsJobsRoute
  '/docs/leads': typeof DocumentationDocsLeadsRoute
  '/docs/screenings': typeof DocumentationDocsScreeningsRoute
  '/docs/themes': typeof DocumentationDocsThemesRoute
  '/cim-screening/$sessionId': typeof ProtectedCimScreeningSessionIdRoute
  '/companies/$uid': typeof ProtectedCompaniesUidRouteWithChildren
  '/companies/new': typeof ProtectedCompaniesNewRoute
  '/deal-opportunities/new': typeof ProtectedDealOpportunitiesNewRoute
  '/deal-opportunities/quick-add': typeof ProtectedDealOpportunitiesQuickAddRoute
  '/investment-themes/new': typeof ProtectedInvestmentThemesNewRoute
  '/investor-leads/new': typeof ProtectedInvestorLeadsNewRoute
  '/investors/new': typeof ProtectedInvestorsNewRoute
  '/leads/new': typeof ProtectedLeadsNewRoute
  '/new/document': typeof ProtectedNewDocumentRoute
  '/profile/$uid': typeof ProtectedProfileUidRoute
  '/screeners/$uid': typeof ProtectedScreenersUidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/deal-opportunities/quick-add': typeof ApiDealOpportunitiesQuickAddRoute
  '/api/health/redis': typeof ApiHealthRedisRoute
  '/api/investor-leads/ingest': typeof ApiInvestorLeadsIngestRoute
  '/api/leads/ingest': typeof ApiLeadsIngestRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/cim-screening': typeof ProtectedCimScreeningIndexRoute
  '/companies': typeof ProtectedCompaniesIndexRoute
  '/deal-opportunities': typeof ProtectedDealOpportunitiesIndexRoute
  '/investment-themes': typeof ProtectedInvestmentThemesIndexRoute
  '/investor-leads': typeof ProtectedInvestorLeadsIndexRoute
  '/leads': typeof ProtectedLeadsIndexRoute
  '/screeners': typeof ProtectedScreenersIndexRoute
  '/companies/$uid/edit': typeof ProtectedCompaniesUidEditRoute
  '/deal-opportunities/$uid/edit': typeof ProtectedDealOpportunitiesUidEditRoute
  '/investment-themes/$uid/edit': typeof ProtectedInvestmentThemesUidEditRoute
  '/investor-leads/$uid/convert': typeof ProtectedInvestorLeadsUidConvertRoute
  '/investor-leads/$uid/edit': typeof ProtectedInvestorLeadsUidEditRoute
  '/investors/$uid/edit': typeof ProtectedInvestorsUidEditRoute
  '/leads/$uid/convert': typeof ProtectedLeadsUidConvertRoute
  '/leads/$uid/edit': typeof ProtectedLeadsUidEditRoute
  '/deal-opportunities/$uid': typeof ProtectedDealOpportunitiesUidIndexRoute
  '/investment-themes/$uid': typeof ProtectedInvestmentThemesUidIndexRoute
  '/investor-leads/$uid': typeof ProtectedInvestorLeadsUidIndexRoute
  '/investors/$uid': typeof ProtectedInvestorsUidIndexRoute
  '/leads/$uid': typeof ProtectedLeadsUidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authentication': typeof AuthenticationRouteRouteWithChildren
  '/_chatbot': typeof ChatbotRouteRouteWithChildren
  '/_documentation': typeof DocumentationRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_chatbot/chat': typeof ChatbotChatRouteWithChildren
  '/_documentation/docs': typeof DocumentationDocsRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/analytics': typeof ProtectedAnalyticsRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/documents': typeof ProtectedDocumentsRoute
  '/_protected/health': typeof ProtectedHealthRoute
  '/_protected/investors': typeof ProtectedInvestorsRouteWithChildren
  '/_protected/jobs': typeof ProtectedJobsRoute
  '/_protected/new': typeof ProtectedNewRouteWithChildren
  '/_protected/screenings': typeof ProtectedScreeningsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/api/trpc': typeof ApiTrpcRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_authentication/auth/error': typeof AuthenticationAuthErrorRoute
  '/_authentication/auth/forgot-password': typeof AuthenticationAuthForgotPasswordRoute
  '/_authentication/auth/login': typeof AuthenticationAuthLoginRoute
  '/_authentication/auth/reset-password': typeof AuthenticationAuthResetPasswordRoute
  '/_authentication/auth/signup': typeof AuthenticationAuthSignupRoute
  '/_authentication/auth/verify-email': typeof AuthenticationAuthVerifyEmailRoute
  '/_chatbot/chat/$id': typeof ChatbotChatIdRoute
  '/_documentation/docs/admin': typeof DocumentationDocsAdminRoute
  '/_documentation/docs/analytics': typeof DocumentationDocsAnalyticsRoute
  '/_documentation/docs/chat': typeof DocumentationDocsChatRoute
  '/_documentation/docs/companies': typeof DocumentationDocsCompaniesRoute
  '/_documentation/docs/deals': typeof DocumentationDocsDealsRoute
  '/_documentation/docs/documents': typeof DocumentationDocsDocumentsRoute
  '/_documentation/docs/faq': typeof DocumentationDocsFaqRoute
  '/_documentation/docs/getting-started': typeof DocumentationDocsGettingStartedRoute
  '/_documentation/docs/investors': typeof DocumentationDocsInvestorsRoute
  '/_documentation/docs/jobs': typeof DocumentationDocsJobsRoute
  '/_documentation/docs/leads': typeof DocumentationDocsLeadsRoute
  '/_documentation/docs/screenings': typeof DocumentationDocsScreeningsRoute
  '/_documentation/docs/themes': typeof DocumentationDocsThemesRoute
  '/_protected/cim-screening/$sessionId': typeof ProtectedCimScreeningSessionIdRoute
  '/_protected/companies/$uid': typeof ProtectedCompaniesUidRouteWithChildren
  '/_protected/companies/new': typeof ProtectedCompaniesNewRoute
  '/_protected/deal-opportunities/new': typeof ProtectedDealOpportunitiesNewRoute
  '/_protected/deal-opportunities/quick-add': typeof ProtectedDealOpportunitiesQuickAddRoute
  '/_protected/investment-themes/new': typeof ProtectedInvestmentThemesNewRoute
  '/_protected/investor-leads/new': typeof ProtectedInvestorLeadsNewRoute
  '/_protected/investors/new': typeof ProtectedInvestorsNewRoute
  '/_protected/leads/new': typeof ProtectedLeadsNewRoute
  '/_protected/new/document': typeof ProtectedNewDocumentRoute
  '/_protected/profile/$uid': typeof ProtectedProfileUidRoute
  '/_protected/screeners/$uid': typeof ProtectedScreenersUidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/deal-opportunities/quick-add': typeof ApiDealOpportunitiesQuickAddRoute
  '/api/health/redis': typeof ApiHealthRedisRoute
  '/api/investor-leads/ingest': typeof ApiInvestorLeadsIngestRoute
  '/api/leads/ingest': typeof ApiLeadsIngestRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_protected/cim-screening/': typeof ProtectedCimScreeningIndexRoute
  '/_protected/companies/': typeof ProtectedCompaniesIndexRoute
  '/_protected/deal-opportunities/': typeof ProtectedDealOpportunitiesIndexRoute
  '/_protected/investment-themes/': typeof ProtectedInvestmentThemesIndexRoute
  '/_protected/investor-leads/': typeof ProtectedInvestorLeadsIndexRoute
  '/_protected/leads/': typeof ProtectedLeadsIndexRoute
  '/_protected/screeners/': typeof ProtectedScreenersIndexRoute
  '/_protected/companies/$uid/edit': typeof ProtectedCompaniesUidEditRoute
  '/_protected/deal-opportunities/$uid/edit': typeof ProtectedDealOpportunitiesUidEditRoute
  '/_protected/investment-themes/$uid/edit': typeof ProtectedInvestmentThemesUidEditRoute
  '/_protected/investor-leads/$uid/convert': typeof ProtectedInvestorLeadsUidConvertRoute
  '/_protected/investor-leads/$uid/edit': typeof ProtectedInvestorLeadsUidEditRoute
  '/_protected/investors/$uid/edit': typeof ProtectedInvestorsUidEditRoute
  '/_protected/leads/$uid/convert': typeof ProtectedLeadsUidConvertRoute
  '/_protected/leads/$uid/edit': typeof ProtectedLeadsUidEditRoute
  '/_protected/deal-opportunities/$uid/': typeof ProtectedDealOpportunitiesUidIndexRoute
  '/_protected/investment-themes/$uid/': typeof ProtectedInvestmentThemesUidIndexRoute
  '/_protected/investor-leads/$uid/': typeof ProtectedInvestorLeadsUidIndexRoute
  '/_protected/investors/$uid/': typeof ProtectedInvestorsUidIndexRoute
  '/_protected/leads/$uid/': typeof ProtectedLeadsUidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/docs'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/health'
    | '/investors'
    | '/jobs'
    | '/new'
    | '/screenings'
    | '/api/chat'
    | '/api/revalidate'
    | '/api/trpc'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/chat/$id'
    | '/docs/admin'
    | '/docs/analytics'
    | '/docs/chat'
    | '/docs/companies'
    | '/docs/deals'
    | '/docs/documents'
    | '/docs/faq'
    | '/docs/getting-started'
    | '/docs/investors'
    | '/docs/jobs'
    | '/docs/leads'
    | '/docs/screenings'
    | '/docs/themes'
    | '/cim-screening/$sessionId'
    | '/companies/$uid'
    | '/companies/new'
    | '/deal-opportunities/new'
    | '/deal-opportunities/quick-add'
    | '/investment-themes/new'
    | '/investor-leads/new'
    | '/investors/new'
    | '/leads/new'
    | '/new/document'
    | '/profile/$uid'
    | '/screeners/$uid'
    | '/api/auth/$'
    | '/api/deal-opportunities/quick-add'
    | '/api/health/redis'
    | '/api/investor-leads/ingest'
    | '/api/leads/ingest'
    | '/api/trpc/$'
    | '/cim-screening/'
    | '/companies/'
    | '/deal-opportunities/'
    | '/investment-themes/'
    | '/investor-leads/'
    | '/leads/'
    | '/screeners/'
    | '/companies/$uid/edit'
    | '/deal-opportunities/$uid/edit'
    | '/investment-themes/$uid/edit'
    | '/investor-leads/$uid/convert'
    | '/investor-leads/$uid/edit'
    | '/investors/$uid/edit'
    | '/leads/$uid/convert'
    | '/leads/$uid/edit'
    | '/deal-opportunities/$uid/'
    | '/investment-themes/$uid/'
    | '/investor-leads/$uid/'
    | '/investors/$uid/'
    | '/leads/$uid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/docs'
    | '/admin'
    | '/analytics'
    | '/dashboard'
    | '/documents'
    | '/health'
    | '/investors'
    | '/jobs'
    | '/new'
    | '/screenings'
    | '/api/chat'
    | '/api/revalidate'
    | '/api/trpc'
    | '/auth/error'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/chat/$id'
    | '/docs/admin'
    | '/docs/analytics'
    | '/docs/chat'
    | '/docs/companies'
    | '/docs/deals'
    | '/docs/documents'
    | '/docs/faq'
    | '/docs/getting-started'
    | '/docs/investors'
    | '/docs/jobs'
    | '/docs/leads'
    | '/docs/screenings'
    | '/docs/themes'
    | '/cim-screening/$sessionId'
    | '/companies/$uid'
    | '/companies/new'
    | '/deal-opportunities/new'
    | '/deal-opportunities/quick-add'
    | '/investment-themes/new'
    | '/investor-leads/new'
    | '/investors/new'
    | '/leads/new'
    | '/new/document'
    | '/profile/$uid'
    | '/screeners/$uid'
    | '/api/auth/$'
    | '/api/deal-opportunities/quick-add'
    | '/api/health/redis'
    | '/api/investor-leads/ingest'
    | '/api/leads/ingest'
    | '/api/trpc/$'
    | '/cim-screening'
    | '/companies'
    | '/deal-opportunities'
    | '/investment-themes'
    | '/investor-leads'
    | '/leads'
    | '/screeners'
    | '/companies/$uid/edit'
    | '/deal-opportunities/$uid/edit'
    | '/investment-themes/$uid/edit'
    | '/investor-leads/$uid/convert'
    | '/investor-leads/$uid/edit'
    | '/investors/$uid/edit'
    | '/leads/$uid/convert'
    | '/leads/$uid/edit'
    | '/deal-opportunities/$uid'
    | '/investment-themes/$uid'
    | '/investor-leads/$uid'
    | '/investors/$uid'
    | '/leads/$uid'
  id:
    | '__root__'
    | '/_authentication'
    | '/_chatbot'
    | '/_documentation'
    | '/_protected'
    | '/_chatbot/chat'
    | '/_documentation/docs'
    | '/_protected/admin'
    | '/_protected/analytics'
    | '/_protected/dashboard'
    | '/_protected/documents'
    | '/_protected/health'
    | '/_protected/investors'
    | '/_protected/jobs'
    | '/_protected/new'
    | '/_protected/screenings'
    | '/api/chat'
    | '/api/revalidate'
    | '/api/trpc'
    | '/_protected/'
    | '/_authentication/auth/error'
    | '/_authentication/auth/forgot-password'
    | '/_authentication/auth/login'
    | '/_authentication/auth/reset-password'
    | '/_authentication/auth/signup'
    | '/_authentication/auth/verify-email'
    | '/_chatbot/chat/$id'
    | '/_documentation/docs/admin'
    | '/_documentation/docs/analytics'
    | '/_documentation/docs/chat'
    | '/_documentation/docs/companies'
    | '/_documentation/docs/deals'
    | '/_documentation/docs/documents'
    | '/_documentation/docs/faq'
    | '/_documentation/docs/getting-started'
    | '/_documentation/docs/investors'
    | '/_documentation/docs/jobs'
    | '/_documentation/docs/leads'
    | '/_documentation/docs/screenings'
    | '/_documentation/docs/themes'
    | '/_protected/cim-screening/$sessionId'
    | '/_protected/companies/$uid'
    | '/_protected/companies/new'
    | '/_protected/deal-opportunities/new'
    | '/_protected/deal-opportunities/quick-add'
    | '/_protected/investment-themes/new'
    | '/_protected/investor-leads/new'
    | '/_protected/investors/new'
    | '/_protected/leads/new'
    | '/_protected/new/document'
    | '/_protected/profile/$uid'
    | '/_protected/screeners/$uid'
    | '/api/auth/$'
    | '/api/deal-opportunities/quick-add'
    | '/api/health/redis'
    | '/api/investor-leads/ingest'
    | '/api/leads/ingest'
    | '/api/trpc/$'
    | '/_protected/cim-screening/'
    | '/_protected/companies/'
    | '/_protected/deal-opportunities/'
    | '/_protected/investment-themes/'
    | '/_protected/investor-leads/'
    | '/_protected/leads/'
    | '/_protected/screeners/'
    | '/_protected/companies/$uid/edit'
    | '/_protected/deal-opportunities/$uid/edit'
    | '/_protected/investment-themes/$uid/edit'
    | '/_protected/investor-leads/$uid/convert'
    | '/_protected/investor-leads/$uid/edit'
    | '/_protected/investors/$uid/edit'
    | '/_protected/leads/$uid/convert'
    | '/_protected/leads/$uid/edit'
    | '/_protected/deal-opportunities/$uid/'
    | '/_protected/investment-themes/$uid/'
    | '/_protected/investor-leads/$uid/'
    | '/_protected/investors/$uid/'
    | '/_protected/leads/$uid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticationRouteRoute: typeof AuthenticationRouteRouteWithChildren
  ChatbotRouteRoute: typeof ChatbotRouteRouteWithChildren
  DocumentationRouteRoute: typeof DocumentationRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  ApiTrpcRoute: typeof ApiTrpcRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDealOpportunitiesQuickAddRoute: typeof ApiDealOpportunitiesQuickAddRoute
  ApiHealthRedisRoute: typeof ApiHealthRedisRoute
  ApiInvestorLeadsIngestRoute: typeof ApiInvestorLeadsIngestRoute
  ApiLeadsIngestRoute: typeof ApiLeadsIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_documentation': {
      id: '/_documentation'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocumentationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chatbot': {
      id: '/_chatbot'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatbotRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/trpc': {
      id: '/api/trpc'
      path: '/api/trpc'
      fullPath: '/api/trpc'
      preLoaderRoute: typeof ApiTrpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/screenings': {
      id: '/_protected/screenings'
      path: '/screenings'
      fullPath: '/screenings'
      preLoaderRoute: typeof ProtectedScreeningsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/new': {
      id: '/_protected/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof ProtectedNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/jobs': {
      id: '/_protected/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof ProtectedJobsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investors': {
      id: '/_protected/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof ProtectedInvestorsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/health': {
      id: '/_protected/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof ProtectedHealthRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/documents': {
      id: '/_protected/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ProtectedDocumentsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/analytics': {
      id: '/_protected/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_documentation/docs': {
      id: '/_documentation/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocumentationDocsRouteImport
      parentRoute: typeof DocumentationRouteRoute
    }
    '/_chatbot/chat': {
      id: '/_chatbot/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatbotChatRouteImport
      parentRoute: typeof ChatbotRouteRoute
    }
    '/_protected/screeners/': {
      id: '/_protected/screeners/'
      path: '/screeners'
      fullPath: '/screeners/'
      preLoaderRoute: typeof ProtectedScreenersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leads/': {
      id: '/_protected/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof ProtectedLeadsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investor-leads/': {
      id: '/_protected/investor-leads/'
      path: '/investor-leads'
      fullPath: '/investor-leads/'
      preLoaderRoute: typeof ProtectedInvestorLeadsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investment-themes/': {
      id: '/_protected/investment-themes/'
      path: '/investment-themes'
      fullPath: '/investment-themes/'
      preLoaderRoute: typeof ProtectedInvestmentThemesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/deal-opportunities/': {
      id: '/_protected/deal-opportunities/'
      path: '/deal-opportunities'
      fullPath: '/deal-opportunities/'
      preLoaderRoute: typeof ProtectedDealOpportunitiesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/companies/': {
      id: '/_protected/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof ProtectedCompaniesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/cim-screening/': {
      id: '/_protected/cim-screening/'
      path: '/cim-screening'
      fullPath: '/cim-screening/'
      preLoaderRoute: typeof ProtectedCimScreeningIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof ApiTrpcRoute
    }
    '/api/leads/ingest': {
      id: '/api/leads/ingest'
      path: '/api/leads/ingest'
      fullPath: '/api/leads/ingest'
      preLoaderRoute: typeof ApiLeadsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/investor-leads/ingest': {
      id: '/api/investor-leads/ingest'
      path: '/api/investor-leads/ingest'
      fullPath: '/api/investor-leads/ingest'
      preLoaderRoute: typeof ApiInvestorLeadsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/redis': {
      id: '/api/health/redis'
      path: '/api/health/redis'
      fullPath: '/api/health/redis'
      preLoaderRoute: typeof ApiHealthRedisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deal-opportunities/quick-add': {
      id: '/api/deal-opportunities/quick-add'
      path: '/api/deal-opportunities/quick-add'
      fullPath: '/api/deal-opportunities/quick-add'
      preLoaderRoute: typeof ApiDealOpportunitiesQuickAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/screeners/$uid': {
      id: '/_protected/screeners/$uid'
      path: '/screeners/$uid'
      fullPath: '/screeners/$uid'
      preLoaderRoute: typeof ProtectedScreenersUidRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile/$uid': {
      id: '/_protected/profile/$uid'
      path: '/profile/$uid'
      fullPath: '/profile/$uid'
      preLoaderRoute: typeof ProtectedProfileUidRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/new/document': {
      id: '/_protected/new/document'
      path: '/document'
      fullPath: '/new/document'
      preLoaderRoute: typeof ProtectedNewDocumentRouteImport
      parentRoute: typeof ProtectedNewRoute
    }
    '/_protected/leads/new': {
      id: '/_protected/leads/new'
      path: '/leads/new'
      fullPath: '/leads/new'
      preLoaderRoute: typeof ProtectedLeadsNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investors/new': {
      id: '/_protected/investors/new'
      path: '/new'
      fullPath: '/investors/new'
      preLoaderRoute: typeof ProtectedInvestorsNewRouteImport
      parentRoute: typeof ProtectedInvestorsRoute
    }
    '/_protected/investor-leads/new': {
      id: '/_protected/investor-leads/new'
      path: '/investor-leads/new'
      fullPath: '/investor-leads/new'
      preLoaderRoute: typeof ProtectedInvestorLeadsNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investment-themes/new': {
      id: '/_protected/investment-themes/new'
      path: '/investment-themes/new'
      fullPath: '/investment-themes/new'
      preLoaderRoute: typeof ProtectedInvestmentThemesNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/deal-opportunities/quick-add': {
      id: '/_protected/deal-opportunities/quick-add'
      path: '/deal-opportunities/quick-add'
      fullPath: '/deal-opportunities/quick-add'
      preLoaderRoute: typeof ProtectedDealOpportunitiesQuickAddRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/deal-opportunities/new': {
      id: '/_protected/deal-opportunities/new'
      path: '/deal-opportunities/new'
      fullPath: '/deal-opportunities/new'
      preLoaderRoute: typeof ProtectedDealOpportunitiesNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/companies/new': {
      id: '/_protected/companies/new'
      path: '/companies/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof ProtectedCompaniesNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/companies/$uid': {
      id: '/_protected/companies/$uid'
      path: '/companies/$uid'
      fullPath: '/companies/$uid'
      preLoaderRoute: typeof ProtectedCompaniesUidRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/cim-screening/$sessionId': {
      id: '/_protected/cim-screening/$sessionId'
      path: '/cim-screening/$sessionId'
      fullPath: '/cim-screening/$sessionId'
      preLoaderRoute: typeof ProtectedCimScreeningSessionIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_documentation/docs/themes': {
      id: '/_documentation/docs/themes'
      path: '/themes'
      fullPath: '/docs/themes'
      preLoaderRoute: typeof DocumentationDocsThemesRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/screenings': {
      id: '/_documentation/docs/screenings'
      path: '/screenings'
      fullPath: '/docs/screenings'
      preLoaderRoute: typeof DocumentationDocsScreeningsRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/leads': {
      id: '/_documentation/docs/leads'
      path: '/leads'
      fullPath: '/docs/leads'
      preLoaderRoute: typeof DocumentationDocsLeadsRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/jobs': {
      id: '/_documentation/docs/jobs'
      path: '/jobs'
      fullPath: '/docs/jobs'
      preLoaderRoute: typeof DocumentationDocsJobsRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/investors': {
      id: '/_documentation/docs/investors'
      path: '/investors'
      fullPath: '/docs/investors'
      preLoaderRoute: typeof DocumentationDocsInvestorsRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/getting-started': {
      id: '/_documentation/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocumentationDocsGettingStartedRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/faq': {
      id: '/_documentation/docs/faq'
      path: '/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocumentationDocsFaqRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/documents': {
      id: '/_documentation/docs/documents'
      path: '/documents'
      fullPath: '/docs/documents'
      preLoaderRoute: typeof DocumentationDocsDocumentsRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/deals': {
      id: '/_documentation/docs/deals'
      path: '/deals'
      fullPath: '/docs/deals'
      preLoaderRoute: typeof DocumentationDocsDealsRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/companies': {
      id: '/_documentation/docs/companies'
      path: '/companies'
      fullPath: '/docs/companies'
      preLoaderRoute: typeof DocumentationDocsCompaniesRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/chat': {
      id: '/_documentation/docs/chat'
      path: '/chat'
      fullPath: '/docs/chat'
      preLoaderRoute: typeof DocumentationDocsChatRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/analytics': {
      id: '/_documentation/docs/analytics'
      path: '/analytics'
      fullPath: '/docs/analytics'
      preLoaderRoute: typeof DocumentationDocsAnalyticsRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_documentation/docs/admin': {
      id: '/_documentation/docs/admin'
      path: '/admin'
      fullPath: '/docs/admin'
      preLoaderRoute: typeof DocumentationDocsAdminRouteImport
      parentRoute: typeof DocumentationDocsRoute
    }
    '/_chatbot/chat/$id': {
      id: '/_chatbot/chat/$id'
      path: '/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatbotChatIdRouteImport
      parentRoute: typeof ChatbotChatRoute
    }
    '/_authentication/auth/verify-email': {
      id: '/_authentication/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthenticationAuthVerifyEmailRouteImport
      parentRoute: typeof AuthenticationRouteRoute
    }
    '/_authentication/auth/signup': {
      id: '/_authentication/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthenticationAuthSignupRouteImport
      parentRoute: typeof AuthenticationRouteRoute
    }
    '/_authentication/auth/reset-password': {
      id: '/_authentication/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthenticationAuthResetPasswordRouteImport
      parentRoute: typeof AuthenticationRouteRoute
    }
    '/_authentication/auth/login': {
      id: '/_authentication/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthenticationAuthLoginRouteImport
      parentRoute: typeof AuthenticationRouteRoute
    }
    '/_authentication/auth/forgot-password': {
      id: '/_authentication/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthenticationAuthForgotPasswordRouteImport
      parentRoute: typeof AuthenticationRouteRoute
    }
    '/_authentication/auth/error': {
      id: '/_authentication/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthenticationAuthErrorRouteImport
      parentRoute: typeof AuthenticationRouteRoute
    }
    '/_protected/leads/$uid/': {
      id: '/_protected/leads/$uid/'
      path: '/leads/$uid'
      fullPath: '/leads/$uid/'
      preLoaderRoute: typeof ProtectedLeadsUidIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investors/$uid/': {
      id: '/_protected/investors/$uid/'
      path: '/$uid'
      fullPath: '/investors/$uid/'
      preLoaderRoute: typeof ProtectedInvestorsUidIndexRouteImport
      parentRoute: typeof ProtectedInvestorsRoute
    }
    '/_protected/investor-leads/$uid/': {
      id: '/_protected/investor-leads/$uid/'
      path: '/investor-leads/$uid'
      fullPath: '/investor-leads/$uid/'
      preLoaderRoute: typeof ProtectedInvestorLeadsUidIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investment-themes/$uid/': {
      id: '/_protected/investment-themes/$uid/'
      path: '/investment-themes/$uid'
      fullPath: '/investment-themes/$uid/'
      preLoaderRoute: typeof ProtectedInvestmentThemesUidIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/deal-opportunities/$uid/': {
      id: '/_protected/deal-opportunities/$uid/'
      path: '/deal-opportunities/$uid'
      fullPath: '/deal-opportunities/$uid/'
      preLoaderRoute: typeof ProtectedDealOpportunitiesUidIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leads/$uid/edit': {
      id: '/_protected/leads/$uid/edit'
      path: '/leads/$uid/edit'
      fullPath: '/leads/$uid/edit'
      preLoaderRoute: typeof ProtectedLeadsUidEditRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/leads/$uid/convert': {
      id: '/_protected/leads/$uid/convert'
      path: '/leads/$uid/convert'
      fullPath: '/leads/$uid/convert'
      preLoaderRoute: typeof ProtectedLeadsUidConvertRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investors/$uid/edit': {
      id: '/_protected/investors/$uid/edit'
      path: '/$uid/edit'
      fullPath: '/investors/$uid/edit'
      preLoaderRoute: typeof ProtectedInvestorsUidEditRouteImport
      parentRoute: typeof ProtectedInvestorsRoute
    }
    '/_protected/investor-leads/$uid/edit': {
      id: '/_protected/investor-leads/$uid/edit'
      path: '/investor-leads/$uid/edit'
      fullPath: '/investor-leads/$uid/edit'
      preLoaderRoute: typeof ProtectedInvestorLeadsUidEditRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investor-leads/$uid/convert': {
      id: '/_protected/investor-leads/$uid/convert'
      path: '/investor-leads/$uid/convert'
      fullPath: '/investor-leads/$uid/convert'
      preLoaderRoute: typeof ProtectedInvestorLeadsUidConvertRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/investment-themes/$uid/edit': {
      id: '/_protected/investment-themes/$uid/edit'
      path: '/investment-themes/$uid/edit'
      fullPath: '/investment-themes/$uid/edit'
      preLoaderRoute: typeof ProtectedInvestmentThemesUidEditRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/deal-opportunities/$uid/edit': {
      id: '/_protected/deal-opportunities/$uid/edit'
      path: '/deal-opportunities/$uid/edit'
      fullPath: '/deal-opportunities/$uid/edit'
      preLoaderRoute: typeof ProtectedDealOpportunitiesUidEditRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/companies/$uid/edit': {
      id: '/_protected/companies/$uid/edit'
      path: '/edit'
      fullPath: '/companies/$uid/edit'
      preLoaderRoute: typeof ProtectedCompaniesUidEditRouteImport
      parentRoute: typeof ProtectedCompaniesUidRoute
    }
  }
}

interface AuthenticationRouteRouteChildren {
  AuthenticationAuthErrorRoute: typeof AuthenticationAuthErrorRoute
  AuthenticationAuthForgotPasswordRoute: typeof AuthenticationAuthForgotPasswordRoute
  AuthenticationAuthLoginRoute: typeof AuthenticationAuthLoginRoute
  AuthenticationAuthResetPasswordRoute: typeof AuthenticationAuthResetPasswordRoute
  AuthenticationAuthSignupRoute: typeof AuthenticationAuthSignupRoute
  AuthenticationAuthVerifyEmailRoute: typeof AuthenticationAuthVerifyEmailRoute
}

const AuthenticationRouteRouteChildren: AuthenticationRouteRouteChildren = {
  AuthenticationAuthErrorRoute: AuthenticationAuthErrorRoute,
  AuthenticationAuthForgotPasswordRoute: AuthenticationAuthForgotPasswordRoute,
  AuthenticationAuthLoginRoute: AuthenticationAuthLoginRoute,
  AuthenticationAuthResetPasswordRoute: AuthenticationAuthResetPasswordRoute,
  AuthenticationAuthSignupRoute: AuthenticationAuthSignupRoute,
  AuthenticationAuthVerifyEmailRoute: AuthenticationAuthVerifyEmailRoute,
}

const AuthenticationRouteRouteWithChildren =
  AuthenticationRouteRoute._addFileChildren(AuthenticationRouteRouteChildren)

interface ChatbotChatRouteChildren {
  ChatbotChatIdRoute: typeof ChatbotChatIdRoute
}

const ChatbotChatRouteChildren: ChatbotChatRouteChildren = {
  ChatbotChatIdRoute: ChatbotChatIdRoute,
}

const ChatbotChatRouteWithChildren = ChatbotChatRoute._addFileChildren(
  ChatbotChatRouteChildren,
)

interface ChatbotRouteRouteChildren {
  ChatbotChatRoute: typeof ChatbotChatRouteWithChildren
}

const ChatbotRouteRouteChildren: ChatbotRouteRouteChildren = {
  ChatbotChatRoute: ChatbotChatRouteWithChildren,
}

const ChatbotRouteRouteWithChildren = ChatbotRouteRoute._addFileChildren(
  ChatbotRouteRouteChildren,
)

interface DocumentationDocsRouteChildren {
  DocumentationDocsAdminRoute: typeof DocumentationDocsAdminRoute
  DocumentationDocsAnalyticsRoute: typeof DocumentationDocsAnalyticsRoute
  DocumentationDocsChatRoute: typeof DocumentationDocsChatRoute
  DocumentationDocsCompaniesRoute: typeof DocumentationDocsCompaniesRoute
  DocumentationDocsDealsRoute: typeof DocumentationDocsDealsRoute
  DocumentationDocsDocumentsRoute: typeof DocumentationDocsDocumentsRoute
  DocumentationDocsFaqRoute: typeof DocumentationDocsFaqRoute
  DocumentationDocsGettingStartedRoute: typeof DocumentationDocsGettingStartedRoute
  DocumentationDocsInvestorsRoute: typeof DocumentationDocsInvestorsRoute
  DocumentationDocsJobsRoute: typeof DocumentationDocsJobsRoute
  DocumentationDocsLeadsRoute: typeof DocumentationDocsLeadsRoute
  DocumentationDocsScreeningsRoute: typeof DocumentationDocsScreeningsRoute
  DocumentationDocsThemesRoute: typeof DocumentationDocsThemesRoute
}

const DocumentationDocsRouteChildren: DocumentationDocsRouteChildren = {
  DocumentationDocsAdminRoute: DocumentationDocsAdminRoute,
  DocumentationDocsAnalyticsRoute: DocumentationDocsAnalyticsRoute,
  DocumentationDocsChatRoute: DocumentationDocsChatRoute,
  DocumentationDocsCompaniesRoute: DocumentationDocsCompaniesRoute,
  DocumentationDocsDealsRoute: DocumentationDocsDealsRoute,
  DocumentationDocsDocumentsRoute: DocumentationDocsDocumentsRoute,
  DocumentationDocsFaqRoute: DocumentationDocsFaqRoute,
  DocumentationDocsGettingStartedRoute: DocumentationDocsGettingStartedRoute,
  DocumentationDocsInvestorsRoute: DocumentationDocsInvestorsRoute,
  DocumentationDocsJobsRoute: DocumentationDocsJobsRoute,
  DocumentationDocsLeadsRoute: DocumentationDocsLeadsRoute,
  DocumentationDocsScreeningsRoute: DocumentationDocsScreeningsRoute,
  DocumentationDocsThemesRoute: DocumentationDocsThemesRoute,
}

const DocumentationDocsRouteWithChildren =
  DocumentationDocsRoute._addFileChildren(DocumentationDocsRouteChildren)

interface DocumentationRouteRouteChildren {
  DocumentationDocsRoute: typeof DocumentationDocsRouteWithChildren
}

const DocumentationRouteRouteChildren: DocumentationRouteRouteChildren = {
  DocumentationDocsRoute: DocumentationDocsRouteWithChildren,
}

const DocumentationRouteRouteWithChildren =
  DocumentationRouteRoute._addFileChildren(DocumentationRouteRouteChildren)

interface ProtectedInvestorsRouteChildren {
  ProtectedInvestorsNewRoute: typeof ProtectedInvestorsNewRoute
  ProtectedInvestorsUidEditRoute: typeof ProtectedInvestorsUidEditRoute
  ProtectedInvestorsUidIndexRoute: typeof ProtectedInvestorsUidIndexRoute
}

const ProtectedInvestorsRouteChildren: ProtectedInvestorsRouteChildren = {
  ProtectedInvestorsNewRoute: ProtectedInvestorsNewRoute,
  ProtectedInvestorsUidEditRoute: ProtectedInvestorsUidEditRoute,
  ProtectedInvestorsUidIndexRoute: ProtectedInvestorsUidIndexRoute,
}

const ProtectedInvestorsRouteWithChildren =
  ProtectedInvestorsRoute._addFileChildren(ProtectedInvestorsRouteChildren)

interface ProtectedNewRouteChildren {
  ProtectedNewDocumentRoute: typeof ProtectedNewDocumentRoute
}

const ProtectedNewRouteChildren: ProtectedNewRouteChildren = {
  ProtectedNewDocumentRoute: ProtectedNewDocumentRoute,
}

const ProtectedNewRouteWithChildren = ProtectedNewRoute._addFileChildren(
  ProtectedNewRouteChildren,
)

interface ProtectedCompaniesUidRouteChildren {
  ProtectedCompaniesUidEditRoute: typeof ProtectedCompaniesUidEditRoute
}

const ProtectedCompaniesUidRouteChildren: ProtectedCompaniesUidRouteChildren = {
  ProtectedCompaniesUidEditRoute: ProtectedCompaniesUidEditRoute,
}

const ProtectedCompaniesUidRouteWithChildren =
  ProtectedCompaniesUidRoute._addFileChildren(
    ProtectedCompaniesUidRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedAnalyticsRoute: typeof ProtectedAnalyticsRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedDocumentsRoute: typeof ProtectedDocumentsRoute
  ProtectedHealthRoute: typeof ProtectedHealthRoute
  ProtectedInvestorsRoute: typeof ProtectedInvestorsRouteWithChildren
  ProtectedJobsRoute: typeof ProtectedJobsRoute
  ProtectedNewRoute: typeof ProtectedNewRouteWithChildren
  ProtectedScreeningsRoute: typeof ProtectedScreeningsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedCimScreeningSessionIdRoute: typeof ProtectedCimScreeningSessionIdRoute
  ProtectedCompaniesUidRoute: typeof ProtectedCompaniesUidRouteWithChildren
  ProtectedCompaniesNewRoute: typeof ProtectedCompaniesNewRoute
  ProtectedDealOpportunitiesNewRoute: typeof ProtectedDealOpportunitiesNewRoute
  ProtectedDealOpportunitiesQuickAddRoute: typeof ProtectedDealOpportunitiesQuickAddRoute
  ProtectedInvestmentThemesNewRoute: typeof ProtectedInvestmentThemesNewRoute
  ProtectedInvestorLeadsNewRoute: typeof ProtectedInvestorLeadsNewRoute
  ProtectedLeadsNewRoute: typeof ProtectedLeadsNewRoute
  ProtectedProfileUidRoute: typeof ProtectedProfileUidRoute
  ProtectedScreenersUidRoute: typeof ProtectedScreenersUidRoute
  ProtectedCimScreeningIndexRoute: typeof ProtectedCimScreeningIndexRoute
  ProtectedCompaniesIndexRoute: typeof ProtectedCompaniesIndexRoute
  ProtectedDealOpportunitiesIndexRoute: typeof ProtectedDealOpportunitiesIndexRoute
  ProtectedInvestmentThemesIndexRoute: typeof ProtectedInvestmentThemesIndexRoute
  ProtectedInvestorLeadsIndexRoute: typeof ProtectedInvestorLeadsIndexRoute
  ProtectedLeadsIndexRoute: typeof ProtectedLeadsIndexRoute
  ProtectedScreenersIndexRoute: typeof ProtectedScreenersIndexRoute
  ProtectedDealOpportunitiesUidEditRoute: typeof ProtectedDealOpportunitiesUidEditRoute
  ProtectedInvestmentThemesUidEditRoute: typeof ProtectedInvestmentThemesUidEditRoute
  ProtectedInvestorLeadsUidConvertRoute: typeof ProtectedInvestorLeadsUidConvertRoute
  ProtectedInvestorLeadsUidEditRoute: typeof ProtectedInvestorLeadsUidEditRoute
  ProtectedLeadsUidConvertRoute: typeof ProtectedLeadsUidConvertRoute
  ProtectedLeadsUidEditRoute: typeof ProtectedLeadsUidEditRoute
  ProtectedDealOpportunitiesUidIndexRoute: typeof ProtectedDealOpportunitiesUidIndexRoute
  ProtectedInvestmentThemesUidIndexRoute: typeof ProtectedInvestmentThemesUidIndexRoute
  ProtectedInvestorLeadsUidIndexRoute: typeof ProtectedInvestorLeadsUidIndexRoute
  ProtectedLeadsUidIndexRoute: typeof ProtectedLeadsUidIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedAnalyticsRoute: ProtectedAnalyticsRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedDocumentsRoute: ProtectedDocumentsRoute,
  ProtectedHealthRoute: ProtectedHealthRoute,
  ProtectedInvestorsRoute: ProtectedInvestorsRouteWithChildren,
  ProtectedJobsRoute: ProtectedJobsRoute,
  ProtectedNewRoute: ProtectedNewRouteWithChildren,
  ProtectedScreeningsRoute: ProtectedScreeningsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedCimScreeningSessionIdRoute: ProtectedCimScreeningSessionIdRoute,
  ProtectedCompaniesUidRoute: ProtectedCompaniesUidRouteWithChildren,
  ProtectedCompaniesNewRoute: ProtectedCompaniesNewRoute,
  ProtectedDealOpportunitiesNewRoute: ProtectedDealOpportunitiesNewRoute,
  ProtectedDealOpportunitiesQuickAddRoute:
    ProtectedDealOpportunitiesQuickAddRoute,
  ProtectedInvestmentThemesNewRoute: ProtectedInvestmentThemesNewRoute,
  ProtectedInvestorLeadsNewRoute: ProtectedInvestorLeadsNewRoute,
  ProtectedLeadsNewRoute: ProtectedLeadsNewRoute,
  ProtectedProfileUidRoute: ProtectedProfileUidRoute,
  ProtectedScreenersUidRoute: ProtectedScreenersUidRoute,
  ProtectedCimScreeningIndexRoute: ProtectedCimScreeningIndexRoute,
  ProtectedCompaniesIndexRoute: ProtectedCompaniesIndexRoute,
  ProtectedDealOpportunitiesIndexRoute: ProtectedDealOpportunitiesIndexRoute,
  ProtectedInvestmentThemesIndexRoute: ProtectedInvestmentThemesIndexRoute,
  ProtectedInvestorLeadsIndexRoute: ProtectedInvestorLeadsIndexRoute,
  ProtectedLeadsIndexRoute: ProtectedLeadsIndexRoute,
  ProtectedScreenersIndexRoute: ProtectedScreenersIndexRoute,
  ProtectedDealOpportunitiesUidEditRoute:
    ProtectedDealOpportunitiesUidEditRoute,
  ProtectedInvestmentThemesUidEditRoute: ProtectedInvestmentThemesUidEditRoute,
  ProtectedInvestorLeadsUidConvertRoute: ProtectedInvestorLeadsUidConvertRoute,
  ProtectedInvestorLeadsUidEditRoute: ProtectedInvestorLeadsUidEditRoute,
  ProtectedLeadsUidConvertRoute: ProtectedLeadsUidConvertRoute,
  ProtectedLeadsUidEditRoute: ProtectedLeadsUidEditRoute,
  ProtectedDealOpportunitiesUidIndexRoute:
    ProtectedDealOpportunitiesUidIndexRoute,
  ProtectedInvestmentThemesUidIndexRoute:
    ProtectedInvestmentThemesUidIndexRoute,
  ProtectedInvestorLeadsUidIndexRoute: ProtectedInvestorLeadsUidIndexRoute,
  ProtectedLeadsUidIndexRoute: ProtectedLeadsUidIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface ApiTrpcRouteChildren {
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

const ApiTrpcRouteChildren: ApiTrpcRouteChildren = {
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}

const ApiTrpcRouteWithChildren =
  ApiTrpcRoute._addFileChildren(ApiTrpcRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticationRouteRoute: AuthenticationRouteRouteWithChildren,
  ChatbotRouteRoute: ChatbotRouteRouteWithChildren,
  DocumentationRouteRoute: DocumentationRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  ApiTrpcRoute: ApiTrpcRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDealOpportunitiesQuickAddRoute: ApiDealOpportunitiesQuickAddRoute,
  ApiHealthRedisRoute: ApiHealthRedisRoute,
  ApiInvestorLeadsIngestRoute: ApiInvestorLeadsIngestRoute,
  ApiLeadsIngestRoute: ApiLeadsIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
